In [1]:
##imports from libraries
import pandas as pd
import numpy as np
import time
from sklearn import linear_model

In [2]:
## Load data and preprocessing:

## reading dataset ''household_power_consumption.txt'' : 
## merging two first columns (date and time) in one column
data= pd.read_csv('household_power_consumption.txt', sep=';', 
                 parse_dates={'dt' : ['Date', 'Time']}, infer_datetime_format=True, 
                 low_memory=False, na_values=['nan','?'], index_col='dt')

In [3]:
## Describe the data:
## count:  The number of not-empty values.
data.describe()

Global_active_power  Global_reactive_power       Voltage  \
count         2.049280e+06           2.049280e+06  2.049280e+06   
mean          1.091615e+00           1.237145e-01  2.408399e+02   
std           1.057294e+00           1.127220e-01  3.239987e+00   
min           7.600000e-02           0.000000e+00  2.232000e+02   
25%           3.080000e-01           4.800000e-02  2.389900e+02   
50%           6.020000e-01           1.000000e-01  2.410100e+02   
75%           1.528000e+00           1.940000e-01  2.428900e+02   
max           1.112200e+01           1.390000e+00  2.541500e+02   

       Global_intensity  Sub_metering_1  Sub_metering_2  Sub_metering_3  
count      2.049280e+06    2.049280e+06    2.049280e+06    2.049280e+06  
mean       4.627759e+00    1.121923e+00    1.298520e+00    6.458447e+00  
std        4.444396e+00    6.153031e+00    5.822026e+00    8.437154e+00  
min        2.000000e-01    0.000000e+00    0.000000e+00    0.000000e+00  
25%        1.400000e+00    0.000000e+00    0.000000e+00    0.000000e+00  
50%        2.600000e+00    0.000000e+00    0.000000e+00    1.000000e+00  
75%        6.400000e+00    0.000000e+00    1.000000e+00    1.700000e+01  
max        4.840000e+01    8.800000e+01    8.000000e+01    3.100000e+01

In [4]:
## Find the number of 'nan' in each column:
data.isnull().sum()

Global_active_power      25979
Global_reactive_power    25979
Voltage                  25979
Global_intensity         25979
Sub_metering_1           25979
Sub_metering_2           25979
Sub_metering_3           25979
dtype: int64

In [5]:
## Find the columns that have 'nan': 
##(This section is not necessary since we can directly go through each column in the next section)
droping_list_all=[]
for j in range(0,7):
    if not data.iloc[:, j].notnull().all():
        droping_list_all.append(j)        
droping_list_all

[0, 1, 2, 3, 4, 5, 6]

In [6]:
## Replace the 'nan' cases in each column with the mean value of that column
## (in order to not change the stochastic parameters):
for j in range(0,7):        
        data.iloc[:,j]=data.iloc[:,j].fillna(data.iloc[:,j].mean())

In [7]:
## Define the first 6 columns as X:
X=data.iloc[:,0:6]


In [8]:
X

Global_active_power  Global_reactive_power  Voltage  \
dt                                                                         
2006-12-16 17:24:00                4.216                  0.418   234.84   
2006-12-16 17:25:00                5.360                  0.436   233.63   
2006-12-16 17:26:00                5.374                  0.498   233.29   
2006-12-16 17:27:00                5.388                  0.502   233.74   
2006-12-16 17:28:00                3.666                  0.528   235.68   
...                                  ...                    ...      ...   
2010-11-26 20:58:00                0.946                  0.000   240.43   
2010-11-26 20:59:00                0.944                  0.000   240.00   
2010-11-26 21:00:00                0.938                  0.000   239.82   
2010-11-26 21:01:00                0.934                  0.000   239.70   
2010-11-26 21:02:00                0.932                  0.000   239.55   

                     Global_intensity  Sub_metering_1  Sub_metering_2  
dt                                                                     
2006-12-16 17:24:00              18.4             0.0             1.0  
2006-12-16 17:25:00              23.0             0.0             1.0  
2006-12-16 17:26:00              23.0             0.0             2.0  
2006-12-16 17:27:00              23.0             0.0             1.0  
2006-12-16 17:28:00              15.8             0.0             1.0  
...                               ...             ...             ...  
2010-11-26 20:58:00               4.0             0.0             0.0  
2010-11-26 20:59:00               4.0             0.0             0.0  
2010-11-26 21:00:00               3.8             0.0             0.0  
2010-11-26 21:01:00               3.8             0.0             0.0  
2010-11-26 21:02:00               3.8             0.0             0.0  

[2075259 rows x 6 columns]

In [9]:
## Define the last column as y
y=data.iloc[:,6]


In [10]:
y

dt
2006-12-16 17:24:00    17.0
2006-12-16 17:25:00    16.0
2006-12-16 17:26:00    17.0
2006-12-16 17:27:00    17.0
2006-12-16 17:28:00    17.0
                       ... 
2010-11-26 20:58:00     0.0
2010-11-26 20:59:00     0.0
2010-11-26 21:00:00     0.0
2010-11-26 21:01:00     0.0
2010-11-26 21:02:00     0.0
Name: Sub_metering_3, Length: 2075259, dtype: float64

In [11]:
X.describe()

Global_active_power  Global_reactive_power       Voltage  \
count         2.075259e+06           2.075259e+06  2.075259e+06   
mean          1.091615e+00           1.237145e-01  2.408399e+02   
std           1.050655e+00           1.120142e-01  3.219643e+00   
min           7.600000e-02           0.000000e+00  2.232000e+02   
25%           3.100000e-01           4.800000e-02  2.390200e+02   
50%           6.300000e-01           1.020000e-01  2.409600e+02   
75%           1.520000e+00           1.920000e-01  2.428600e+02   
max           1.112200e+01           1.390000e+00  2.541500e+02   

       Global_intensity  Sub_metering_1  Sub_metering_2  
count      2.075259e+06    2.075259e+06    2.075259e+06  
mean       4.627759e+00    1.121923e+00    1.298520e+00  
std        4.416490e+00    6.114397e+00    5.785470e+00  
min        2.000000e-01    0.000000e+00    0.000000e+00  
25%        1.400000e+00    0.000000e+00    0.000000e+00  
50%        2.800000e+00    0.000000e+00    0.000000e+00  
75%        6.400000e+00    0.000000e+00    1.000000e+00  
max        4.840000e+01    8.800000e+01    8.000000e+01

In [12]:
## Each feature (column) is scaled in its own terms... 
## All of the features should be normalized in order to have the compatible data
x_mean=X.mean()
x_std= X.std()
X=(X-x_mean)/x_std

In [13]:
## Now we have almost zero-mean data with unit variance, as shown below
X.describe()

Global_active_power  Global_reactive_power       Voltage  \
count         2.075259e+06           2.075259e+06  2.075259e+06   
mean         -9.357604e-13           5.003686e-13 -5.873640e-11   
std           1.000000e+00           1.000000e+00  1.000000e+00   
min          -9.666490e-01          -1.104453e+00 -5.478824e+00   
25%          -7.439309e-01          -6.759364e-01 -5.652359e-01   
50%          -4.393591e-01          -1.938547e-01  3.731532e-02   
75%           4.077311e-01           6.096149e-01  6.274429e-01   
max           9.546788e+00           1.130469e+01  4.134043e+00   

       Global_intensity  Sub_metering_1  Sub_metering_2  
count      2.075259e+06    2.075259e+06    2.075259e+06  
mean      -1.997329e-13   -2.570006e-14    2.134187e-13  
std        1.000000e+00    1.000000e+00    1.000000e+00  
min       -1.002552e+00   -1.834888e-01   -2.244450e-01  
25%       -7.308426e-01   -1.834888e-01   -2.244450e-01  
50%       -4.138488e-01   -1.834888e-01   -2.244450e-01  
75%        4.012781e-01   -1.834888e-01   -5.159822e-02  
max        9.911092e+00    1.420877e+01    1.360330e+01

In [14]:
##Adding intercept row 
X["intercept"]=1

In [15]:
X

Global_active_power  Global_reactive_power   Voltage  \
dt                                                                          
2006-12-16 17:24:00             2.973748               2.627216 -1.863517   
2006-12-16 17:25:00             4.062592               2.787910 -2.239335   
2006-12-16 17:26:00             4.075917               3.341411 -2.344936   
2006-12-16 17:27:00             4.089242               3.377121 -2.205169   
2006-12-16 17:28:00             2.450266               3.609234 -1.602618   
...                                  ...                    ...       ...   
2010-11-26 20:58:00            -0.138594              -1.104453 -0.127299   
2010-11-26 20:59:00            -0.140498              -1.104453 -0.260854   
2010-11-26 21:00:00            -0.146209              -1.104453 -0.316761   
2010-11-26 21:01:00            -0.150016              -1.104453 -0.354032   
2010-11-26 21:02:00            -0.151919              -1.104453 -0.400621   

                     Global_intensity  Sub_metering_1  Sub_metering_2  \
dt                                                                      
2006-12-16 17:24:00          3.118368       -0.183489       -0.051598   
2006-12-16 17:25:00          4.159919       -0.183489       -0.051598   
2006-12-16 17:26:00          4.159919       -0.183489        0.121249   
2006-12-16 17:27:00          4.159919       -0.183489       -0.051598   
2006-12-16 17:28:00          2.529665       -0.183489       -0.051598   
...                               ...             ...             ...   
2010-11-26 20:58:00         -0.142140       -0.183489       -0.224445   
2010-11-26 20:59:00         -0.142140       -0.183489       -0.224445   
2010-11-26 21:00:00         -0.187425       -0.183489       -0.224445   
2010-11-26 21:01:00         -0.187425       -0.183489       -0.224445   
2010-11-26 21:02:00         -0.187425       -0.183489       -0.224445   

                     intercept  
dt                              
2006-12-16 17:24:00          1  
2006-12-16 17:25:00          1  
2006-12-16 17:26:00          1  
2006-12-16 17:27:00          1  
2006-12-16 17:28:00          1  
...                        ...  
2010-11-26 20:58:00          1  
2010-11-26 20:59:00          1  
2010-11-26 21:00:00          1  
2010-11-26 21:01:00          1  
2010-11-26 21:02:00          1  

[2075259 rows x 7 columns]

In [16]:
## You can observe the shape of data by 
print(X.shape)
print(y.shape)

(2075259, 7)
(2075259,)


In [17]:
# Get the sumber of samples
N=X.shape[0]

# Define the identity matrix
I=np.identity(X.shape[1])
indx_intercept=X.shape[1]-1
I[indx_intercept][indx_intercept]=0
I

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [18]:
## Closed form solution and optimal linear regressor

# Define lambda here:
lam = 1/N # change the value

start1 = time.time()
## Calculate the closed-form solution here:
closed_form_sol= np.linalg.inv(X.T @ X + lam*N*I) @ X.T @ y
end1 = time.time()


reg = linear_model.Ridge(alpha=lam)

start2 = time.time()
## Find the optimal linear regressor here:
reg.fit(X,y)
end2 = time.time()

# Show the running time for the closed-form approach and the itterative algorithm
print(end1-start1)
print(end2-start2)

0.2887868881225586
0.04687929153442383


In [19]:
## Show the optimal linear regressor based on the colsed-form solution
closed_form_sol

0    42.585299
1     0.198422
2    -0.623129
3   -35.399833
4    -2.471475
5    -2.236698
6     6.458447
dtype: float64

In [20]:
## Show the optimal linear regressor based on the itterative algorithm
reg.coef_

array([ 42.60868266,   0.19889588,  -0.62345423, -35.42364539,
        -2.47128404,  -2.23650622,   0.        ])

In [21]:
reg.intercept_

6.458447357118318

In [22]:
## Show the estimated y (w^T*X) based on the closed-form solution
a=np.dot(X, closed_form_sol)
a

array([24.95811535, 34.72220112, 35.07867491, ...,  7.80064554,
        7.66174181,  7.60970853])

In [23]:
## Show the estimated y (w^T*X) based on the itterative algorithm
reg.predict(X)


array([24.95520363, 34.7201471 , 35.07726248, ...,  7.80119093,
        7.6622103 ,  7.61014766])

In [24]:
## Check the gap between closed-form solution and the itterative one
reg.predict(X)- a


array([-0.00291172, -0.00205403, -0.00141243, ...,  0.00054539,
        0.00046848,  0.00043913])